In [77]:
# 1 
import numpy as np

In [79]:
# 2 Create a null vector of size 10
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [81]:
# 3 Create a null vector of size 10 but the fifth value which is 1
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [83]:
# 4 Create a vector with values ranging from 10 to 49
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [85]:
# 5 Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
# 6 Find indices of non-zero elements from [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
indices_non_zero_elements = np.nonzero(arr)
indices_non_zero_elements

(array([0, 1, 4]),)

In [89]:
# 7 Create a 3x3 identity matrix

identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
# 8 Create a 3x3x3 array with random values
array = np.random.random ((3, 3, 3))
array

array([[[0.63722738, 0.87118676, 0.02304254],
        [0.06277146, 0.33862259, 0.85953239],
        [0.78834118, 0.60023607, 0.06237888]],

       [[0.85129485, 0.19414309, 0.48759927],
        [0.96694342, 0.05895144, 0.97330156],
        [0.74752093, 0.12677329, 0.71573709]],

       [[0.22633592, 0.30733501, 0.79566328],
        [0.01143878, 0.70307489, 0.7870186 ],
        [0.33208271, 0.98706621, 0.77420095]]])

In [93]:
#9  Create a 10x10 array with random values and find the minimum and maximum values
array = np.random.random ((10,10))
array

array([[0.20488101, 0.16440177, 0.57922927, 0.5268114 , 0.28538168,
        0.87858128, 0.72351194, 0.09329026, 0.54979597, 0.83520673],
       [0.98200334, 0.63186572, 0.0579001 , 0.08044741, 0.81545509,
        0.60324075, 0.93038409, 0.16412763, 0.86085105, 0.49163989],
       [0.03555292, 0.49810097, 0.26936724, 0.68788897, 0.07622875,
        0.19000998, 0.24904143, 0.59701351, 0.7762217 , 0.70351838],
       [0.11668234, 0.3624848 , 0.56361751, 0.03843598, 0.83499176,
        0.28618344, 0.30345115, 0.0934997 , 0.42311362, 0.94166384],
       [0.34379634, 0.78266041, 0.29616608, 0.13282148, 0.12758612,
        0.24891724, 0.88076776, 0.66604561, 0.97571837, 0.94264707],
       [0.43720187, 0.97013293, 0.21582949, 0.48888523, 0.26734977,
        0.91044593, 0.37698218, 0.34193493, 0.75868581, 0.16757103],
       [0.03220413, 0.5119372 , 0.92232642, 0.60842705, 0.81511192,
        0.37238834, 0.90502777, 0.75617668, 0.41216332, 0.19156733],
       [0.19977318, 0.85650631, 0.6806195

In [95]:
min = array.min()
max = array.max()
print(min,max)

0.017882841329710963 0.9820033398300372


In [97]:
# 10 Create a random vector of size 30 and find the mean value 
random_vector = np.random.random(30)
random_vector

array([0.12258711, 0.76553732, 0.6250091 , 0.5058692 , 0.1593568 ,
       0.7584349 , 0.50365179, 0.50223418, 0.94482776, 0.60094878,
       0.84221026, 0.33020769, 0.0237392 , 0.12702226, 0.02660377,
       0.97324706, 0.78871853, 0.18194374, 0.14276138, 0.6448272 ,
       0.86870756, 0.99911966, 0.01578009, 0.7697604 , 0.56251984,
       0.61407503, 0.99477583, 0.60694019, 0.79985964, 0.60209214])

In [99]:
mean = np.mean(random_vector)
mean

0.5467789466738651

In [120]:
# 11 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
matrix = np.diag([1, 2, 3, 4], k=-1)
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [144]:
# 12 Normalize a 5x5 random matrix 

matrix = np.random.randn(5, 5)  
matrix.mean()
z_score = (matrix - np.mean(matrix, axis=1)) / np.std(matrix, axis=1)
z_score 

array([[-0.39248018, -1.43753359,  1.38208884, -1.53205507, -2.1977964 ],
       [ 1.06495314,  0.97217705,  0.87331361, -1.44025184, -1.70262673],
       [ 0.9367373 ,  0.01621279,  0.48672635, -1.0926483 ,  0.31757043],
       [ 1.40462319, -1.43081161, -1.28231286,  0.13732206,  0.45897986],
       [ 0.29734064,  2.01895466,  2.87045328,  0.57930246, -0.38797033]])

In [150]:
# 13  How to find common values between two arrays? 
array1 = np.array([1,3,5,7,9,11])
array2 = np.array([9,10,11,12,13,14])
common_values = np.intersect1d(array1, array2)
common_values

array([ 9, 11])

In [166]:
# 14 Create a random vector of size 10 and sort it
vector = np.random.rand(10)
sorted_vect = np.sort(vector)
sorted_vect

array([0.01639413, 0.16994877, 0.41573058, 0.49583903, 0.61989339,
       0.65290586, 0.66230464, 0.67927705, 0.86145091, 0.92010294])

In [210]:
# 15 Create random vector of size 10 and replace the maximum value by 0
vector = np.random.rand(10)
max_value = arr.max()
vector[max_value] = 0
vector

array([0.32267115, 0.82314382, 0.45716159, 0.5345879 , 0.        ,
       0.93741525, 0.64697252, 0.86824002, 0.56335962, 0.61924661])

In [208]:
# 16 Subtract the mean of each row of a matrix 
matrix  = np.random.randn(5, 5) 
row_mean = matrix.mean(axis=1, keepdims=True)
matrix_diff = matrix - row_mean
matrix_diff

array([[ 0.19950338, -1.29210124, -0.6076497 ,  1.27057541,  0.42967216],
       [-0.7709691 ,  1.18776126,  0.80001866,  0.38289096, -1.59970178],
       [-0.98081721,  0.17548857,  0.40578738, -0.3045503 ,  0.70409156],
       [ 0.61224885, -0.14327225, -3.04609249,  1.23144   ,  1.34567588],
       [ 1.19101371,  0.10484568,  0.24345542, -0.8374644 , -0.70185041]])

In [212]:
# 17 How to get the n largest values of an array
np.random.seed(42)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
indices = np.argsort(Z)[-n:]
largest_values = Z[indices]
largest_values

array([9995, 9996, 9997, 9998, 9999])

In [214]:
# 18 Create a random 5*3 matrix and replace items that are larger than 4 by their squares  
np.random.seed(42)
p = np.arange(15).reshape(5,3)
print(p)
np.where (p>4, np.square(p), p)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[  0,   1,   2],
       [  3,   4,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]])